baseurl = "https://pates.tech/"
languageCode = "en-us"
title = "Tech notes"
theme = "kiera"
disqusShortname = "pates-tech-notes"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "UA-17391504-9"
# Number of posts per page
paginate = 100

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:title/"

[params]
    title = "Tech notes"
    subtitle = ""
    copyright = "Anton Pates 2018-2019"
    paginate = 100

    # You can choose between green, orange, red and blue.
    themecolor = "green"

    # Link custom assets relative to /static
    favicon   = "favicon.ico"
    customCSS = []
    customJS  = []

    # To provide some metadata for search engines and the about section in the footer
    # feel free to add a few information about you and your website.
    name = "Anton Pates"
    bio = "software engineer"
    description = ""

    # Link your social networks (optional)
    location = ""
    twitter = ""
    linkedin = "anton-pates-5b906290"
    googleplus = ""
    facebook = ""
    instagram = ""
    github = "AntonPates"
    gitlab = ""
    bitbucket = ""

    # Customize or translate the strings
    keepReadingStr = "Keep reading"
    backtotopStr = "Back to top"
    shareStr = "Share"
    pageNotFoundTitle = "404 - Page not found"

[author]
    name = "Anton Pates"       #Author name
    github = "AntonPates"     #Github username
    gitlab = ""     #Gitlab username
    linkedin = "anton-pates-5b906290"   #LinkedIn username
    facebook = ""   #Facebook username
    twitter = ""    #Twitter username
    instagram = ""  #Instagram username

[[menu.main]]
name = "Posts"
weight = 1
identifier = "posts"
url = "/posts"